# Generated by Django 4.2.1 on 2023-11-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employeename', models.CharField(max_length=255)),
                ('companyid', models.CharField(max_length=255, unique=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRoleMapData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employeeid', models.BigIntegerField()),
                ('roleid', models.BigIntegerField()),
                ('assignedon', models.DateField(blank=True, null=True)),
                ('assignedby', models.CharField(blank=True, max_length=255, null=True)),
                ('lastupdated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rolename', models.CharField(max_length=255, unique=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('payrange', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
