# Generated by Django 4.2.1 on 2023-11-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
